[2024-07-05T09:26:06.514+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.process_user scheduled__2024-07-04T00:00:00+00:00 [queued]>
[2024-07-05T09:26:06.560+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.process_user scheduled__2024-07-04T00:00:00+00:00 [queued]>
[2024-07-05T09:26:06.565+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-07-05T09:26:06.570+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-07-05T09:26:06.572+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-07-05T09:26:06.622+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): process_user> on 2024-07-04 00:00:00+00:00
[2024-07-05T09:26:06.643+0000] {standard_task_runner.py:55} INFO - Started process 82435 to run task
[2024-07-05T09:26:06.674+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'scheduled__2024-07-04T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp2jwc2s8f']
[2024-07-05T09:26:06.684+0000] {standard_task_runner.py:83} INFO - Job 65: Subtask process_user
[2024-07-05T09:26:06.976+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.process_user scheduled__2024-07-04T00:00:00+00:00 [running]> on host 409ff340d891
[2024-07-05T09:26:07.249+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2024-07-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-04T00:00:00+00:00
[2024-07-05T09:26:07.288+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 15, in _process_user
    user= user['results'][0]
TypeError: 'NoneType' object is not subscriptable
[2024-07-05T09:26:07.325+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=process_user, execution_date=20240704T000000, start_date=20240705T092606, end_date=20240705T092607
[2024-07-05T09:26:07.360+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 65 for task process_user ('NoneType' object is not subscriptable; 82435)
[2024-07-05T09:26:07.393+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-07-05T09:26:07.455+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
